### ISSUE TITLE
ClickEvent Enhancement

### ISSUE THREAD

**Issue by ZioPagnotta** [KyoriPowered/adventure#189]
It would be great if ClickEvent's Action could be a lambda expression like: 
`Component.text("Test").clickEvent(<lamda expression>);`

Is there a chance that this could be added in future?

**Comment by derklaro** [comment]
How do you think this should work? There are only some available actions and they are executed in the client not sent to the server.

**Comment by ZioPagnotta** [comment]
Ops, i didn't wrote how it can be useful.
It's useful because to do something such as **add a player in a list** we have to run a command.

**Comment by zml2008** [comment]
Yeah, this is not doable in Adventure itself - callbacks are normally implemented using a command with a click event that executes that command serverside. 

Some platforms like SpongeAPI 8 provide this support - because they have the combination of Adventure and a commands system that can be tightly integrated. Most don't - luckily callbacks are pretty simple to implement in a plugin subcommand.
