### ISSUE TITLE
Add a way to send individual title, subtitle & time packet

### ISSUE THREAD

**Issue by TheMode** [KyoriPowered/adventure#314]
The current `Title` interface makes it impossible to reproduce vanilla's /title command as described here https://www.digminecraft.com/game_commands/title_command.php

The reason being that all components are annotated by `@NonNull`, I have no idea how 1.17 will affect this but I do not expect the command to change.

**Comment by kashike** [comment]
One option is to make the properties in `Title` `@Nullable` instead?

**Comment by kezz** [comment]
> One option is to make the properties in `Title` `@Nullable` instead?

Yeah this is definitely my favourite option. The only downside being that it is potentially breaking change for developers who are relying on that contract.

Some other ideas me and @TheMode were floating about were  adding individual title methods like `Title#title(Component)` and `Title#subtitle(Component)` with corresponding methods to check if the title has a title or subtitle. Additionally, a method in `Audience` to simple send an updated set of times, perhaps `Audience#titleTimes(Title.Times)`, which would let users specify the times directly.

Another option is to leave the standard method and add a big fancy builder for a title that allows the individual components to be nullable if not set. This is potentially quite a nice idea and could be coupled with the previous ideas in order to break the return types nicely without breaking any functionality for creating titles.

A final and perhaps lazy solution is to just add methods in audience to send the title and subtitle individually.

Obviously the cleanest and most simple solution is to just make everything nullable, but I thought I'd float some ideas about! It could be a nice opportunity to improve the title system a bit.

**Comment by kashike** [comment]
> Some other ideas me and @TheMode were floating about were adding individual title methods like `Title#title(Component)` and `Title#subtitle(Component)` with corresponding methods to check if the title has a title or subtitle.
> 

Could you clarify what you mean with this?

**Comment by kezz** [comment]
> > Some other ideas me and @TheMode were floating about were adding individual title methods like `Title#title(Component)` and `Title#subtitle(Component)` with corresponding methods to check if the title has a title or subtitle.
> > 
> 
> Could you clarify what you mean with this?

So the send title method remains the same, everything remains `@NonNull` with notes that it will always return at least an empty component. Then new methods are added that allow the creation of a title with only one or a combination of it's constituent parts. Additionally, in order to allow people to determine if the title parts are empty because they have been sent to empty or are empty because they are missing, you would add some methods like `#hasTitle` and `#hasSubtitle`.

**Comment by kezz** [comment]
Closed in 655f9e00f58af97add37e1169d1274442f9446d8.
