### ISSUE TITLE
Click and hover event arguments are handled differently

### ISSUE THREAD

**Issue by kezz** [KyoriPowered/adventure#661]
Hover events need quotes if they have internal tags but click events do not. This is a regression(?) from 4.2.0-SNAPSHOT where both needed quotes.

**Comment by rymiel** [comment]
Hover events don't need quotes if they only use `miniMessage` replacement tags, not `component` ones; this cursed thing passes:
```java
@Test
void testSomething() {
  final String input = "<hover:show_text:hello <feline>>test</hover>";
  final Component expected = Component.text("test").hoverEvent(Component.text("hello cat"));
  this.assertParsedEquals(expected, input, miniMessage("feline", "cat"));
}
```
Click events just happen to *only* accept `miniMessage` replacements.
I guess those replacements are substituted before the whole `TagPart` thing even happens, so it doesn't care about quotes

**Comment by rymiel** [comment]
Furthermore, `miniMessage` replacements can lead to some sneaky modification of what would otherwise be "syntactically-invalid" minimessage, although i don't think there's really an *easy* way to "fix" that without detracting from what the intended purpose of `miniMessage` replacements is. (other than somehow requiring such replacements to be syntactically valid minimessage and escape the symbols otherwise, which sounds very complicated)
And in any case, if breaking syntax is a concern for the user, `raw` replacements could just be used instead.
Consider the following example test, only a slight modification of the previous (and also passes)
```java
@Test
void testSomething() {
  final String input = "<hover:show_text:hello <feline>test</hover>";
  final Component expected = Component.text("test").hoverEvent(Component.text("hello cat"));
  this.assertParsedEquals(expected, input, miniMessage("feline", "cat>"));
}
```
the hover tag isn't fully formed as it's missing a closing `>`, however the placeholder puts it there and it is picked up on the next pass

**Comment by rymiel** [comment]
I had an idea that would fix this by making `parsed` placeholders return parser *tokens* instead of pure strings, but that would theoretically limit the amount of valid syntax by **forcing** these placeholders contain valid minimessage text and am unsure of other consequences.
I'm proposing that this isn't a bug and that we don't subset the syntax to fix this inconsistency
Unless it is desired to get this syntax-breaking change in for 4.10.0

**Comment by zml2008** [comment]
I agree -- I'm not sure we can really avoid this issue. Longer-term I think we'd like to find an alternative to pre-process tags that doesn't have to be a separate parse pass, but at that point we'd just deprecate `PreProcess` tags and introduce something else.
