### ISSUE TITLE
Toasts 🍞 

### ISSUE THREAD

**Issue by PikaMug** [KyoriPowered/adventure#688]
When advancements (MC 1.12+) are obtained, a sliding toast notification displays in the top-right corner. Are there any plans for Adventure to provide a presentation layer for this UI? If not, would you consider it?

**Comment by kezz** [comment]
There are currently no plans for this. It's a rather complicated system to maintain. Similarly to a scoreboard api, although it would be nice to have, it's something that would require considerable work to be supported on various implementations and the platform builds.

**Comment by zml2008** [comment]
I've looked into this a bit -- it's honestly not as bad as I'd feared, it looks like servers can add advancements pretty easily. The challenge for Adventure is that these advancements can accept `ItemStack`s, which we don't really have a good representation for in API (and we really are trying to stay away from inventory, since that's fairly complex, and an area that's both difficult to implement on proxies, and likely to tread on existing API in our native platforms). I think you'd be better off adding API to the relevant platforms directly that uses `Components`. If you then need to write something cross-platform, you can have a small(er) abstraction library that just calls those implementations.
